### ISSUE TITLE
Final checklist

### ISSUE THREAD

**Issue by willu47** [ClimateCompatibleGrowth/nismod_teaching_kit#1]
# Lecture Block 1
## Lecture 1.2
- [x] The Sendai Framework on Disaster Risk Reduction link gives me an “access denied” page. I have asked Dan for an updated link, which is: https://www.preventionweb.net/files/43291_sendaiframeworkfordrren.pdf 
- [x] Figure 1.2.4 – reference is S.Thacker et al. 2018 – remove “S.” (which will then also remove it in the text where this reference is cited, hopefully!
- [x] Figure 1.2.5 – year of reference should be 2020, not 12020
## Lecture 1.3
- [x] S.Thacker et al. 2019 – remove “S.”
- [x] S Thacker et al., 2018 – remove “S.”
- [x] Second bullet point in “A closer look at achieving the SDGs through infrastructure services” has a typo – should be “collection (transport) services” not “collection (transport)Services”
- [ ] All figures are very blurry?
## Lecture 1.4
- [x] Daniel Adshead et al., 2021 – remove “Daniel”
## Quiz for Lecture 1
something weird with the spacing after “a.” “b.” and “c.”

# Lecture Block 2
## Lecture 2.1
- [x] The reference “Ipcc and Report 2018” should be “IPCC 2018”
## Lecture 2.2
- [x] Figure 2.2.2 missing
## Lecture 2.4
- [x] Figure 2.4.1 is missing
## Quiz for Lecture 2
something weird with the spacing after “a.” “b.” and “c.” for question 6 & 8.

# Lecture Block 3
## Lecture 3.1
- [x] Adshead et al., n.d. – should be “Adshead et al., 2018”. The year of that report is 2018
## Lecture 3.3
- [x] Figure 3.3.1 – citation is wrong. Should be “Intergovernmental Panel on Climate Change 2014” – should then hopefully also fix the issue of where the report is cited within the text and other figure captions
## Lecture 3.4
- [x] Adshead et al., n.d. – should be “Adshead et al., 2018”. The year of that report is 2018
# Quiz for Lecture 3
Question 8 should read “Fuldauer et al. 2019 prioritised….” 

# Lecture Block 4
## Lecture 4.1
- [x] Figure 4.1.1 – reference should read “based on data from UNDESA 2019”
- [x] Within the figure caption of figure 4.1.1 there is “# Infrastructure as long-lived assets” which should be a section title
- [x] Figure 4.1.2 – reference should read “based on data from GIHub 2020”
- [x] In the 3rd paragraph after figure 4.1.2, there is a “# Scenario analysis for infrastructure investments” which should be a heading of the next section
- [x] Within the figure caption of figure 4.1.3 there is “# Shared Socio-economic Pathways (SSPs)” – this should be a section title. 
- [x] “# Infrastructure drivers” should be a section title
- [x] Within the caption of figure 4.1.4 is “# Summary” which should be a section title
## Lecture 4.2
- [x] The reference “Administration 2017” should be “EIA 2017”
- [x] The reference “Programme 2019” should be “UNESCO 2019”
## Lecture 4.3
- [x] The reference “Economic and Affairs 2019” should be “UNDESA 2019”
- [x] The reference “Bank 2021” should be “World Bank 2021”
- [x] First sentence under “Other chronic effects and climate change” section – join references to “Lempert and Groves, 2010; Haasnoot et al., 2013”
## Lecture 4.4
- [x] The reference “D et al. 2018” should be “Adshead et al. 2018”
- [x] The reference “D. et al. 2020” should be “Adshead et al. 2020”
- [x] The reference “Bank 2014” should be “World Bank 2014”
- [x] The reference “Economic and Affairs 2019” should be “UNDESA 2019”
- [x] The reference “Bank 2021” should be “World Bank 2021”

# Lecture Block 5
## Lecture 5.1
- [x] Figure 5.4.1 is missing (actually 5.1.4)

# Lecture Block 6
## Lecture 6.3
- [x] The reference “L. Fuldauer et al., n.d.” should be “Fuldauer et al. 2018”
- [x] The reference “L.I. Fuldauer et al. 2019” should be “Fuldauer et al. 2019”
## Lecture 6.4
- [x] The reference “L.I. Fuldauer et al. 2019” should be “Fuldauer et al. 2019”
- [x] The reference “L. Fuldauer et al. n.d.” should be “Fuldauer et al. 2018”

# Lecture Block 7
## Lecture 7.1
- [x] The reference “HK, B, and M 2016” should be “Anheier, Lorentz and Fratzscher, 2016” or “Anheier et al. 2016”
- [x] The reference “D 2018” should be “Saha 2018”
- [x] Figure 7.1.1 – reference should be “Cohen-Shacham et al. 2016”
## Lecture 7.2
- [x] The reference “J. 1999” should be “Malczewski 1999”
- [x] The reference “L. 1978” should be “Cohon 1978”
## Lecture 7.3
- [x] The reference “Neufville R and S 2011” should be “Neufville and Scholtes 2011”
## Lecture 7.4
- [x] The reference “D et al. 2018” should be “Adshead et al. 2018”
- [x] The reference “D et al. 2020” should be “Adshead et al. 2020”

# Lecture Block 8
## Lecture 8.3
- [x] The reference “Bloemendaal and others 2019” should be “Bloemendal et al. 2019”

# Lecture Block 9
## Lecture 9.1
- [x] The reference “Jim W. Hall et al. 2017” should be “Hall et al. 2017”
- [x] The reference “Jim W. Hall et al. 2016” should be “Hall et al. 2016”
- [x] Figure 9.1.2 missing
- [x] Figure 9.1.4 missing

# Lecture Block 10
## Lecture 10.1
- [x] “Summary” section of lecture 10.1 is not a proper heading title
## Lecture 10.2
- [x] Section “Multiple asset failures” is not a proper heading title

# Lecture Block 11
## Lecture 11.2
- [x] Reference “R. Pante et al. 2018” should be “Pant et al. 2018”
- [x] Reference “Raghav Pant et al. 2018” should be “Pant et al. 2018”
## Lecture 11.3
- [x] The reference “R. Pant et al. 2018” should be “Pant et al. 2018”
- [x] The section “Identifying which populations are indirectly served by infrastructure assets” is not a proper heading title
- [x] The reference “Raghav Pant et al. 2020” should be “Pant et al. 2020”

# Lecture Block 12
## Lecture 12.4
- [ ] Figure are extremely blurry?

# Lecture Block 13
## Lecture 13.4
- [x] The reference “Lena I. Fuldauer et al. 2019” should be “Fuldauer et al. 2019”
- [x] The caption of Figure 13.4.1 has a lot of links of sciencedirect articles? It is meant to look like something like this: 
 
- [x] The reference “L.I. Fuldauer, Thacker and Hall 2021” should be “Fuldauer, Thacker and Hall 2021”
## Lecture 13 Quiz – Spacing is inconsistent in Question 4

# Lecture Block 14
## Lecture 14.4
- [ ] Figure 14.4.2 very blurry
## Lecture 14 Quiz
Spacing on Question 2, option b is off.

# Lecture Block 15
## Lecture 15.1
- [x] The reference “NbS Digital Dialogues n.d.” should be “NbS Digital Dialogues 2020”
- [x] The Sendai Framework on Disaster Risk Reduction link in Table 15.1.1 gives me an “access denied” page. I have asked for an updated link, which is: https://www.preventionweb.net/files/43291_sendaiframeworkfordrren.pdf 
- [x] The reference in figure 15.1.2 “E Cohen-Shacham, G Walters and S Maginnis 2016” should be “Cohen-Shacham, Walters and Maginnis 2016”
## Lecture 15.2
- [x] The reference “Valerie Kapos. Sylvia Wicander 2019” should be “Kapos et al. 2019”
- [x] The reference “Nations 2015” should be “United Nations 2015”
- [x] Figure 15.2.8 should be removed and the text above adjusted – I had done this, so it may just be a matter of re-uploading the mini-lecture from sharepoint
## Lecture 15.3
- [x] The reference “Valerie Kapos. Sylvia Wicander 2019” should be “Kapos et al. 2019”
- [x] The reference “Anderson et al.” has a square bracket in front? 
## Lecture 15.4
- [x] The reference “Hub and Oxford Economics 2017” should be “Global Infrastructure Hub 2017”
- [x] The reference “Valerie Kapos. Sylvia Wicander 2019” should be “Kapos et al. 2019”
- [x] The reference in figure 15.1.2 “E Cohen-Shacham, G Walters and S Maginnis 2016” should be “Cohen-Shacham, Walters and Maginnis 2016”
- [x] The reference “UNOPS and University n.d.” should be “UNOPS 2019”

# Lecture Block 16
## Lecture 16.1
- [x] Figure 16.1.1 is missing
- [x] Formatting of table 16.1.1: In nature-based solutions column. The text “surrounding rivers and …..” should be within the bullet point on “Riparian buffers:…”. Similarly  in the “Coastal/Tidal” row, the text saying “restoration to anchor sediments…” should follow on from “Mangrove protections and …”
  - [x] Similarly, in the column of Co-benefits, the text “wild-sourced food…” should be within the bullet point on “Increased availability of..”
- [x] The reference “Nations 2018” should be “United Nations 2018”

## Lecture 16.2

- [x] The reference “Losada et al. (2018)” has a square bracket in front?
- [x] The reference “Bank 2016” should be “World Bank 2016”
- [x] Formatting of table 16.2.1: In nature-based solutions column. The text “saltmarshes, mangrove,…..” should be within the bullet point on “Protect remaining intertidal…”. Similarly  in the “Storm damage” row, the text saying “restoration can dissipate wave…” should follow on from “Coastal marsh and dune management …”. Further down in the pollution row as well.
- [x] Would it be possible to format this table so that it looks better?

## Lecture 16.3

- [x] The reference “Agency 2015” should be “European Environment Agency 2015” or “EEA 2015”
- [x] The formatting of the text within table 16.3.1 should be fixed so it’s easy to read
- [x] The references “[Stokes et al. (2014); ADPC2020]” are in square brackets and not in the same style.
- [x] The reference “[IUCN2021]” just above figure 16.3.1 is in square brackets

## Lecture 16.4

- [x] Figure 16.4.2 missing
- [x] Figure 16.4.3 missing
- [x] Figure 16.4.4 missing

## Lecture 16 Quiz 

– [ ] Spacing of answers is off for Question 1

# Lecture Block 17
## Lecture 17.1
- [x] The reference “Valerie Kapos. Sylvia Wicander 2019” should be “Kapos et al. 2019”
- [x] The reference in figure 15.1.2 “Cohen-Shacham E, G Walters G., Janzen, C., and Maginnis 2016” should be “Cohen-Shacham et al. 2016”
- [x] The reference “Tremolet S. & Karres N 2020” should be “Tremolet and Karres 2020”
## Lecture 17.2
- [x] The formatting of the text within table 17.2.1 should be fixed so it’s easy to read
- [x] Figure caption 17.2.1 – the caption is in a heading format
## Lecture 17.3
- [x] There is a reference that isn’t formatted properly: “[@Madramootoo&Dodds1994]” at the end of the first paragraph under the heading “Integrating NbS in rivers, canals and lakes”
- [x] The reference “Nations 2016” should be “United Nations 2016”
- [x] The reference “Valerie Kapos. Sylvia Wicander 2019” should be “Kapos et al. 2019”
- [x] The reference “Development Bank 2019” should be “Asian Development Bank 2019”
- [x] The reference “Commission n.d.” should be “European Commission n.d.”
- [x] The reference “Life Elia n.d.” should be “Life Elia 2021”
## Lecture 17.4
- [x] The caption in figure 17.4.5 should have the reference “Kapos et al. 2019”
- [x] There is a reference that isn’t formatted properly: “[@GINW2013]”
- [x] There is  a reference that isn’t formatted properly: “[@Turhan&Akkurt2018]”
- [x] There is a reference that isn’t formatted properly: “[@Stenfors2019; Bratman et al. (2015)]”

# Lecture Block 18
## Lecture 18.2
- [x] The reference “Cohen-Shacham, E., Walters, G., Janzen, C. and Maginnis 2016” should be “Cohen-Shacham et al. 2016”
- [x] None of the links within 18.2.2 work for me – do they for you? If not, I will ask Robyn (author of this lecture) to see whether she can update the links or whether we need to remove them.
## Lecture 18.3
- [x] The reference “Bank 2016” should be “World Bank 2016”
## Lecture 18.4
- [x] The reference “Cohen-Shacham, E., Walters, G., Janzen, C. and Maginnis 2016” should be “Cohen-Shacham et al. 2016”
- [x] The reference “Naumann et al. 2011” has a space in front of it

# Lecture Block 19
## Lecture 19.1
- [x] Can we change the reference “Organisation for Economic Co-operation and Development 2017” to “OECD 2017”?
## Lecture 19.3
- [x] Can we change the reference “Organisation for Economic Co-operation and Development 2017” to “OECD 2017”?
## Lecture 19.4
- [x] Figure 19.4.3 is missing

# Lecture Block 20
Nothing wrong with this lecture block
